Add dirty check in CI (#3)
Signed-off-by: James Orson <jamesaorson@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  ci:
     runs-on: ubuntu-latest
 
     steps:
@@ -25,3 +25,12 @@ jobs:
       - name: Render
         run: |
           make render
+
+      - name: Check Check for uncommitted changes
+        if: github.event_name != 'workflow_dispatch'
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "Error: Uncommitted changes found. Please commit the rendered files."
+            git status
+            exit 1
+          fi
